### ISSUE TITLE
Config new branch gh-pages

### ISSUE THREAD

**Issue by boss3g** [boss3g/deploy-example#6]
branch gh-pages erro.

**Comment by kaykeeb3** [comment]
This error occurs because the GitHub Action is trying to authenticate with the remote repository to publish to the `gh-pages` branch, but the credentials provided are either invalid or missing.  

[ ] Check the token  
[ ] Incorrectly configured branch or repository  
[ ] Token not added as a secret  
[ ] Remote URL error

**Comment by boss3g** [comment]
This error occurs because the GitHub Action is trying to authenticate with the remote repository to publish to the gh-pages branch, but the credentials provided are either invalid or missing.

[x] Check the token
[] Incorrectly configured branch or repository
[] Token not added as a secret
[] Remote URL error

Solved! Deployment to actions completed

**Comment by boss3g** [comment]
Solved. ✅
